server:
  port: 9001
spring:
  application:
    name: nacos-payment-provider
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/video2022?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848 #Nacos服务注册中心地址
      config:
        server-addr: localhost:8848 #Nacos作为配置中心地址
        file-extension: yml #指定yaml格式的配置
#        group: DEV_GROUP
#        namespace: ecf4267b-5123-432c-9850-09c2f6dd18a1 #<------------指定namespace

management:
  endpoints:
    web:
      exposure:
        include: '*'

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.ZhangYM.entities    # 所有Entity别名类所在包

# 日志配置
logging:
  level:
    com.ZhangYM: debug
    org.springframework: warn
